"""create evenement table clean

Revision ID: c6e4c3d1d480
Revises: 
Create Date: 2025-04-29 17:49:47.495378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6e4c3d1d480'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evenements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_evenement', sa.Date(), nullable=False),
    sa.Column('lieu', sa.String(length=255), nullable=False),
    sa.Column('budget_estime', sa.Integer(), nullable=True),
    sa.Column('besoins_logistiques', sa.Text(), nullable=True),
    sa.Column('statut', sa.Enum('EN_ATTENTE', 'VALIDE', 'REFUSE', 'EN_PREPARATION', 'PRET', 'ANNULE', name='event_statut_enum'), nullable=False),
    sa.Column('commentaire_refus', sa.Text(), nullable=True),
    sa.Column('cree_par', sa.Integer(), nullable=False),
    sa.Column('est_etudiant', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='evenement'
    )
    op.create_index(op.f('ix_evenement_evenements_id'), 'evenements', ['id'], unique=False, schema='evenement')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evenement_evenements_id'), table_name='evenements', schema='evenement')
    op.drop_table('evenements', schema='evenement')
    # ### end Alembic commands ###
